
import { Lesson, Milestone } from './types';

export const LESSONS: Lesson[] = [
  { id: 1, title: "Introducing AdonisJS", module: "Ep 1" },
  { id: 2, title: "Before We Begin", module: "Ep 1" },
  { id: 3, title: "Creating A New AdonisJS 6 Project", module: "Ep 1" },
  { id: 4, title: "Project Structure", module: "Ep 1" },
  { id: 5, title: "VS Code Extensions and Configuration", module: "Ep 1" },
  { id: 6, title: "Routes and How To Create Them", module: "Ep 2" },
  { id: 7, title: "Rendering a View for a Route", module: "Ep 2" },
  { id: 8, title: "Linking Between Routes", module: "Ep 2" },
  { id: 9, title: "Loading A Movie Using Route Parameters", module: "Ep 2" },
  { id: 10, title: "Validating Route Parameters", module: "Ep 2" },
  { id: 11, title: "Vite and Our Assets", module: "Ep 2" },
  { id: 12, title: "Setting Up Tailwind CSS", module: "Ep 2" },
  { id: 13, title: "Reading and Supporting Markdown Content", module: "Ep 2" },
  { id: 14, title: "Listing Movies from their Markdown Files", module: "Ep 2" },
  { id: 15, title: "Extracting Reusable Code with Services", module: "Ep 2" },
  { id: 16, title: "Cleaning Up Routes with Controllers", module: "Ep 2" },
  { id: 17, title: "Defining A Structure for our Movie using Models", module: "Ep 2" },
  { id: 18, title: "Singleton Services and the Idea of Caching", module: "Ep 2" },
  { id: 19, title: "Environment Variables and their Validation", module: "Ep 2" },
  { id: 20, title: "Improved Caching with Redis", module: "Ep 2" },
  { id: 21, title: "Deleting Items and Flushing our Redis Cache", module: "Ep 2" },
  { id: 22, title: "Quick Start Apps with Custom Starter Kits", module: "Ep 2" },
  { id: 23, title: "Easy Imports with NodeJS Subpath Imports", module: "Ep 2" },
  { id: 24, title: "EdgeJS Templating Basics", module: "Ep 3" },
  { id: 25, title: "HTML Attribute and Class Utilities", module: "Ep 3" },
  { id: 26, title: "Making A Reusable Movie Card Component", module: "Ep 3" },
  { id: 27, title: "Component Tags, State, and Props", module: "Ep 3" },
  { id: 28, title: "Use Slots To Make A Button Component", module: "Ep 3" },
  { id: 29, title: "Extracting A Layout Component", module: "Ep 3" },
  { id: 30, title: "State vs Share Data Flow", module: "Ep 3" },
  { id: 31, title: "Share vs Global Data Flow", module: "Ep 3" },
  { id: 32, title: "Form Basics and CSRF Protection", module: "Ep 3" },
  { id: 33, title: "HTTP Method Spoofing HTML Forms", module: "Ep 3" },
  { id: 34, title: "Easy SVG Icons with Edge Iconify", module: "Ep 3" },
  { id: 35, title: "Configuring Lucid and our Database Connection", module: "Ep 4" },
  { id: 36, title: "Understanding our Database Schema", module: "Ep 4" },
  { id: 37, title: "Introducing and Defining Database Migrations", module: "Ep 4" },
  { id: 38, title: "The Flow of Migrations", module: "Ep 4" },
  { id: 39, title: "Introducing Lucid Models", module: "Ep 4" },
  { id: 40, title: "Defining Our Models", module: "Ep 4" },
  { id: 41, title: "The Basics of CRUD", module: "Ep 4" },
  { id: 42, title: "Defining Required Data with Seeders", module: "Ep 4" },
  { id: 43, title: "Stubbing Fake Data with Model Factories", module: "Ep 4" },
  { id: 44, title: "Querying Our Movies with the Query Builder", module: "Ep 4" },
  { id: 45, title: "Unmapped and Computed Model Properties", module: "Ep 4" },
  { id: 46, title: "Altering Tables with Migrations", module: "Ep 4" },
  { id: 47, title: "Adding A Profile Model, Migration, Factory, and Controller", module: "Ep 4" },
  { id: 48, title: "SQL Parameters and Injection Protection", module: "Ep 4" },
  { id: 49, title: "Reusable Query Statements with Model Query Scopes", module: "Ep 4" },
  { id: 50, title: "Tapping into Model Factory States", module: "Ep 4" },
  { id: 51, title: "Querying Recently Released and Coming Soon Movies", module: "Ep 4" },
  { id: 52, title: "Generating A Unique Movie Slug With Model Hooks", module: "Ep 4" },
  { id: 53, title: "Defining One-to-One Relationships Within Lucid Models", module: "Ep 5" },
  { id: 54, title: "Model Factory Relationships", module: "Ep 5" },
  { id: 55, title: "Querying Relationships and Eager Vs Lazy Loading", module: "Ep 5" },
  { id: 56, title: "Cascading and Deleting Model Relationships", module: "Ep 5" },
  { id: 57, title: "Defining One to Many Relationships with Lucid Models", module: "Ep 5" },
  { id: 58, title: "Seeding Movies with One to Many Model Factory Relationships", module: "Ep 5" },
  { id: 59, title: "Listing A Director's Movies with Relationship Existence Queries", module: "Ep 5" },
  { id: 60, title: "Listing and Counting a Writer's Movies", module: "Ep 5" },
  { id: 61, title: "Using Eager and Lazy Loading to Load A Movie's Writer and Director", module: "Ep 5" },
  { id: 62, title: "Defining Many-To-Many Relationships and Pivot Columns", module: "Ep 5" },
  { id: 63, title: "Many-To-Many Model Factory Relationships", module: "Ep 5" },
  { id: 64, title: "A Deep Dive Into Relationship CRUD with Models", module: "Ep 5" },
  { id: 65, title: "How To Create Factory Relationships from a Pool of Data", module: "Ep 5" },
  { id: 66, title: "How To Query, Sort, and Filter by Pivot Table Data", module: "Ep 5" },
  { id: 67, title: "Posting and Accepting Form Data", module: "Ep 6" },
  { id: 68, title: "Validating Form Data with VineJS", module: "Ep 6" },
  { id: 69, title: "Displaying Validation Errors and Validating from our Request", module: "Ep 6" },
  { id: 70, title: "Reusing Old Form Values After A Validation Error", module: "Ep 6" },
  { id: 71, title: "Creating An EdgeJS Form Input Component", module: "Ep 6" },
  { id: 72, title: "Creating A Login Form and Validator", module: "Ep 6" },
  { id: 73, title: "How To Create A Custom VineJS Validation Rule", module: "Ep 6" },
  { id: 74, title: "AdonisJS 6 Session Authentication in 15 Minutes", module: "Auth" },
  { id: 75, title: "Authenticating A Newly Registered User", module: "Ep 7" },
  { id: 76, title: "The Flow of Middleware", module: "Ep 7" },
  { id: 77, title: "Checking For and Populating an Authenticated User", module: "Ep 7" },
  { id: 78, title: "Logging Out An Authenticated User", module: "Ep 7" },
  { id: 79, title: "Logging In An Existing User", module: "Ep 7" },
  { id: 80, title: "Remembering A User's Authenticated Session", module: "Ep 7" },
  { id: 81, title: "Protecting Routes with Auth, Guest, and Admin Middleware", module: "Ep 7" },
  { id: 82, title: "Creating A Movie List Page", module: "Ep 8" },
  { id: 83, title: "Filtering A Query By Pattern Likeness", module: "Ep 8" },
  { id: 84, title: "Filtering Our List by Movie Status", module: "Ep 8" },
  { id: 85, title: "How To Apply A Dynamic Sort Filter To Your Query", module: "Ep 8" },
  { id: 86, title: "Joining SQL Tables To Order By A Related Column", module: "Ep 8" },
  { id: 87, title: "Validating Query String Filter Values", module: "Ep 8" },
  { id: 88, title: "How To Paginate Filtered Query Results", module: "Ep 8" },
  { id: 89, title: "Pagination First, Last, Next, and Previous Buttons", module: "Ep 8" },
  { id: 90, title: "Defining A Many-To-Many Pivot Table Model", module: "Ep 9" },
  { id: 91, title: "Toggling A Movie in an Authenticated User's Watchlist", module: "Ep 9" },
  { id: 92, title: "Listing and Filtering User Watchlist Items", module: "Ep 9" },
  { id: 93, title: "Allowing Users To Toggle A Movie As Watched", module: "Ep 9" },
  { id: 94, title: "Filtering By User's Watched Status", module: "Ep 9" },
  { id: 95, title: "Defining A Composite Unique Constraint", module: "Ep 9" },
  { id: 96, title: "AdonisJS 6 Access Token Authentication in 20 Minutes", module: "Auth" },
  { id: 97, title: "Persist Filters Easily with Lucid's Query String Method", module: "Ep 9" },
  { id: 98, title: "How to Create and Fix Missing User Profiles in Your Application", module: "Ep 10" },
  { id: 99, title: "Using Dependency Injection to Update A User's Profile", module: "Ep 10" },
  { id: 100, title: "Saving All Or Nothing with Database Transactions", module: "Ep 10" },
  { id: 101, title: "Uploading and Displaying User Avatar Images", module: "Ep 10" },
  { id: 102, title: "Displaying A User's Profile", module: "Ep 10" },
  { id: 103, title: "Filtering, Preloading, and Sorting By Relationship", module: "Ep 10" },
  { id: 104, title: "Creating An Admin Layout", module: "Ep 11" },
  { id: 105, title: "Counting Stats for our Admin Dashboard", module: "Ep 11" },
  { id: 106, title: "Paginated Admin Movie Table", module: "Ep 11" },
  { id: 107, title: "Allowing Admins to Create Movies", module: "Ep 11" },
  { id: 108, title: "Allowing Admins to Update Movies and Clear Values", module: "Ep 11" },
  { id: 109, title: "How To Use One Form to Create or Edit Movies", module: "Ep 11" },
  { id: 110, title: "Uploading Movie Cover Images in our Create or Edit Form", module: "Ep 11" },
  { id: 111, title: "Using A Wildcard Route Param to Download Storage Images", module: "Ep 11" },
  { id: 112, title: "Posting Objects, Arrays, and an Array of Objects in HTML Forms", module: "Ep 11" },
  { id: 113, title: "Managed Transactions and Syncing Movie Cast Members", module: "Ep 11" },
  { id: 114, title: "Allowing Admins to Delete Movies and their Relationships", module: "Ep 11" },
  { id: 115, title: "Thank You for Watching!", module: "Ep 11" },
  { id: 116, title: "Three Approaches for Organizing your Business Logic", module: "Pro" },
  { id: 117, title: "How To Make A Simple AdonisJS 6 Package", module: "Pro" },
  { id: 118, title: "What Is InertiaJS?", module: "Inertia" },
  { id: 119, title: "What We'll Be Building", module: "Inertia" },
  { id: 120, title: "Creating Our AdonisJS App With InertiaJS", module: "Inertia" },
  { id: 121, title: "SSR vs CSR", module: "Inertia" },
  { id: 122, title: "Setting Up TailwindCSS, Shadcn-Vue, & Auto Imports", module: "Inertia" },
  { id: 123, title: "The Flow of Pages and Page Props", module: "Inertia" },
  { id: 124, title: "Sharing Data from AdonisJS to Vue via Inertia", module: "Inertia" },
  { id: 125, title: "Linking Between Pages & Page State Flow", module: "Inertia" },
  { id: 126, title: "The Link Component and Programmatic Linking", module: "Inertia" },
  { id: 127, title: "Global Components and Hydration Mismatch", module: "Inertia" },
  { id: 128, title: "Partial and Lazy Data Loading and Evaluation", module: "Inertia" },
  { id: 129, title: "Creating A Layout", module: "Inertia" },
  { id: 130, title: "Default Layouts & Overwriting", module: "Inertia" },
  { id: 131, title: "What Code Can & Can't Be Shared", module: "Inertia" },
  { id: 132, title: "Inertia Form Basics", module: "Inertia" },
  { id: 133, title: "Specifying Page Titles & Meta Tags", module: "Inertia" },
  { id: 134, title: "Form Validation & Displaying Errors", module: "Inertia" },
  { id: 135, title: "Creating A Lucid Model Mixin", module: "Misc" },
  { id: 136, title: "Generate DTOs for Lucid Models", module: "Misc" },
  { id: 137, title: "How To Use Model Query Builder Macros", module: "Misc" },
  { id: 138, title: "3 Easy Ways to Split Route Definitions", module: "Misc" },
  { id: 139, title: "New Unique & Exists Validation Overloads", module: "Misc" },
  { id: 140, title: "Dump & Die Debugging (Short)", module: "Misc" },
  { id: 141, title: "Dump & Die Debugging (Full)", module: "Misc" },
  { id: 142, title: "Install & Configure TailwindCSS 4 with Vite", module: "Misc" },
  { id: 143, title: "How to Install TailwindCSS 4 (Quick)", module: "Misc" }
];

export const MILESTONES: Milestone[] = [
  {
    id: 0,
    name: "Marco 0: Start + Landing Page",
    description: "Configuração inicial e criação da página de vendas.",
    maxLessonId: 12,
    features: ["Criar o projeto", "Rotas básicas", "Vite + Tailwind", "Landing Page Home"]
  },
  {
    id: 1,
    name: "Marco 1: Site da Barbearia",
    description: "Identidade visual e site público.",
    maxLessonId: 31,
    features: ["Componentes EdgeJS", "Layout Reutilizável", "Navbar/Footer", "Template por barbearia"]
  },
  {
    id: 2,
    name: "Marco 2: Formulários",
    description: "Interação com o usuário via forms.",
    maxLessonId: 33,
    features: ["Form POST + CSRF", "Solicitar acesso grátis", "Agendamento (UI)"]
  },
  {
    id: 3,
    name: "Marco 3: Banco + CRUD",
    description: "Persistência de dados.",
    maxLessonId: 41,
    features: ["Migrations + Models", "CRUD de Serviços", "CRUD de Barbearias", "Salvar agendamentos"]
  },
  {
    id: 4,
    name: "Marco 4: Demo / Seeders",
    description: "Dados de teste para demonstração.",
    maxLessonId: 43,
    features: ["Seeders", "Factories", "Populando dados reais fictícios"]
  },
  {
    id: 5,
    name: "Marco 5: Relacionamentos",
    description: "Gestão de clientes e histórico.",
    maxLessonId: 66,
    features: ["Relacionamentos 1-1, 1-N, N-N", "Pivot tables", "Filtros avançados", "Histórico de clientes"]
  },
  {
    id: 6,
    name: "Marco 6: Validação + Login",
    description: "Segurança e autenticação profissional.",
    maxLessonId: 81,
    features: ["VineJS Validators", "Session Auth (Login/Logout)", "Middlewares", "Painel Protegido"]
  },
  {
    id: 7,
    name: "Marco 7: Agenda Completa",
    description: "Agenda online com busca e paginação.",
    maxLessonId: 89,
    features: ["Busca por padrão", "Filtro por status", "Paginação completa", "Sort dinâmico"]
  },
  {
    id: 8,
    name: "Marco 8: Perfil + Fotos",
    description: "Upload de imagens e branding.",
    maxLessonId: 103,
    features: ["Upload de Avatar", "Galeria de Fotos", "Perfil Público", "Sorting por relação"]
  },
  {
    id: 9,
    name: "Marco 9: Painel Admin",
    description: "Dashboard de gestão e métricas.",
    maxLessonId: 115,
    features: ["Admin Layout", "Métricas (Stats)", "Gestão Completa (Create/Edit/Delete)", "Managed Transactions"]
  },
  {
    id: 10,
    name: "Marco 10: Organização PRO",
    description: "Arquitetura escalável e limpa.",
    maxLessonId: 116,
    features: ["Business Logic Operations", "Services / Use Cases", "Estrutura modular", "Escalabilidade"]
  }
];
